### ISSUE TITLE
Hitting an error when trying to run wordmerge

### ISSUE THREAD

**Issue by URBabylab** [SeedlingsBabylab/wordmerge#4]
I'm trying to run the script and keep hitting this error:

Traceback (most recent call last):
  File "wordmerge.py", line 328, in <module>
    fix_me_csv = sys.argv[5]
IndexError: list index out of range

I've tried running it on the new (batch-merged) merged.csv as well as the original (pre-batch merging) basic level .csv.

**Comment by andreiamatuni** [comment]
This error should be fixed now
